name: call reusable workflow
on: [push]
jobs:
    call-reusable-workflow:
        runs-on: ubuntu-latest
        steps: 
            - name: calling reusable workflow
              uses: puttur225411/githubAction/.github/workflows/reusable-wrokflow-same-as-workflowrun.yaml@main
              with:
                config-path: .github/workflows

