name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: print a string
        run: echo "Hello"
      - name: multiline command
        run: |
          node -v
          npm -v

  parallel-macos-job:
    runs-on: macos-latest
    steps:
      - name: view sw version
        run: sw_vers
  
  dependdant-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo windows string
        run: Write-Output Windows string
      - name: error steps
        run: deosnot exist