name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: called from different workflow
        run: echo "called from different workflow"
